library:
  source-dirs: src
tests:
  nlps-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unicode-show
    - foldl
    - nlps
    - vector
    - text
    - turtle
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- unicode-show
- foldl
- base >= 4.7 && < 5
- vector
- text
- turtle
name: nlps
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/nlps
license: BSD3
executables:
  nlps-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nlps
    - vector
    - text
    - turtle
description: Please see the README on GitHub at <https://github.com/githubuser/nlps#readme>
